### ISSUE TITLE
Переодически в консоле вылетает 403. На работу не влияет.

### ISSUE THREAD

**Issue by underlow** [InfoWings/Knowledge-Net#176]

**Comment by underlow** [comment]
@sreznick 
Кажется, это нормально. Фронт получает токен, через 5 минут токен протухает - и получается 403. После чего посылается refresh, и жизнь продолжается.
Если говорить более обобщенно и принципиально - все, что пишется в консоль - информация для разработчика и не является частью функциональности приложения с точки зрения пользователя.
Если никаких видимых эффектов нет, кроме записи в консоль, это вообще не предмет бага.
Хотя, за бдительность спасибо.

**Comment by sreznick** [comment]
not an issue
