### ISSUE TITLE
Невозможно удалить использованное в объекте значение справочника

### ISSUE THREAD

**Issue by underlow** [InfoWings/Knowledge-Net#248]
Значение справочника, которое уже использовано в качестве значения  свойства в объекте, невозможно удалить

Ошибка в консоли:

ServerApi.kt:113 POST [http://cs1.reflexia.com/api/book/item/remove] 400 ()
CoroutineExceptionHandler.kt:43 Jt \{message_8yp7un$\_0: "JSON at 1: Expected '\{, kind: CLASS'", cause_th0jdv$\_0: null, name: "IllegalArgumentException", stack: "IllegalArgumentException: JSON at 1: Expected '\{, …n7$ ([http://cs1.reflexia.com/bundle.js:20:112866)"\}|http://cs1.reflexia.com/bundle.js:20:112866)%22%7D]

**Comment by kochkr** [comment]
This issue duplicates #260 , which is already in sprint 12
