### ISSUE TITLE
Failed test: Linked entities view

### ISSUE THREAD

**Issue by airtest-qa** [InfoWings/Knowledge-Net#323]
Subject <Subject 1> on the list of subjects. Aspect (<Aspect 1>, <Subject 1> on the list of subjects).

1. On the subject tab click linked entities button for the subject <Subject 1>. 
Expected Result:
The list of linked entities that includes aspect <Aspect 1> is shown.

Actual result:
Все плохо!!

![](index.php?/attachments/get/5)

T268: Linked entities view
https://airtest.testrail.io/index.php?/tests/view/268

**Comment by tushkanova** [comment]
Duplicate. Integration test.
