### ISSUE TITLE
Failed test: Reference book removal: used in object

### ISSUE THREAD

**Issue by airtest-qa** [InfoWings/Knowledge-Net#324]
Reference book <Book 1> with item <Item 1> that is used for some object <Object 1>.

1. Remove whole reference book <Book 1>.

Expected Result:
The reference book and all its items are removed. Item<Item 1> is showed for <Object 1> (edit and view mode), but it is not possible to use the item for other objects.

Actual result:
After reference book removal <Item 1> is still visible for object <Object 1> on objects list, but is non-visible in <Object 1> edit mode.
![image](https://user-images.githubusercontent.com/28750408/45623642-b1739880-ba90-11e8-9c82-4eae4f13db92.png)
![image](https://user-images.githubusercontent.com/28750408/45623654-b8021000-ba90-11e8-9cb6-85eff4493706.png)

T333: Reference book removal: used in object
https://airtest.testrail.io/index.php?/tests/view/333

**Comment by tushkanova** [comment]
More detailed description in #337
