### ISSUE TITLE
Failed test: Subject removal: with linked entities

### ISSUE THREAD

**Issue by airtest-qa** [InfoWings/Knowledge-Net#356]
Subject with linked entities on the list of subjects.

1. Delete the subject with linked entities.
Expected Result:
After additional confirmation, the subject is deleted and is not on the list of subjects.
2. Reload subject page.
Expected Result:
The deleted subject is not on the list of subjects.

Actual result:
Deleted subject is shown after page update.

T635: Subject removal: with linked entities
https://airtest.testrail.io/index.php?/tests/view/635

**Comment by underlow** [comment]
The issue can be reproduced if you reload subjects really fast.
I'm not sure I've found cause, but it works. Should be tested carefully though
