### ISSUE TITLE
Failed test: Fuzzy search: clean search results

### ISSUE THREAD

**Issue by airtest-qa** [InfoWings/Knowledge-Net#357]
Some aspects on the list of aspects.

1. Input some string to aspect name input.
Expected Result:
Searching results for string should appear.
2. Clean aspect name input.
Expected Result:
Searching results should be cleaned.
3. Select some aspect from the list. 
Expected Result:
There should be no searching results in corresponding area.

Actual result:
The search results are not hidden when clearing the aspect inputs using the “x” button and when selecting other aspect.

T692: Fuzzy search: clean search results
https://airtest.testrail.io/index.php?/tests/view/692

**Comment by samovl** [comment]
"Select some aspect from the list.
Expected Result:
There should be no searching results in corresponding area." - it is INCORRECT, from my point of view. There are not any "select list" in Input field in new aspect mode and search result of nearest aspects has to be shown all time ( until submitting ).
