### ISSUE TITLE
Failed test: Cyclic links

### ISSUE THREAD

**Issue by airtest-qa** [InfoWings/Knowledge-Net#360]
Global aspects <Aspect 1> and <Aspect 2>  on the list of aspects.

1. Add property to the aspect <Aspect 1>
Expected Result:
The form for property input is appeared. 
2. Enter <Aspect 1> to the filed Aspect of the property form.
Expected Result:
It should be no global aspect <Aspect 1> among the suggested options.

3. Add property with the global aspect <Aspect 1> to the global aspect <Aspect 2>.
Expected Result:
Global aspect <Aspect 2> has the property  with global aspect <Aspect 1>.
4. Add property to the aspect <Aspect 1>.
Expected Result:
The form for property input is appeared. 
5. Enter <Aspect 2> to the filed Aspect of the property form.
Expected Result:
It should be neither global aspect <Aspect 2> nor aspect <Aspect 1> itself among the suggested options.

Actual result of step 5: aspect <Aspect 1> is on the list of possible properties for itself. However it is impossible to add it as a property because error is appear.

T629: Cyclic links
https://airtest.testrail.io/index.php?/tests/view/629

**Comment by tushkanova** [comment]
Failed to reproduce.
