### ISSUE TITLE
Check correctness object Primary Business key constraint validation  - use case insert object by API

### ISSUE THREAD

**Issue by samovl** [InfoWings/Knowledge-Net#375]

**Comment by sreznick** [comment]
It is not business key violation in stict sense.
When object Obj is created on subject Subj, then Subj is deleted, new subject with name Subj is created, then nobody forbids one to create another Obj with new subject names Subj.
I looks like correct behaviour for me.

May be it makes sense to discuss it. 

@samovl

**Comment by underlow** [comment]
If we're talking about object dups on cs1 then I did not recreate subject before insertion

**Comment by underlow** [comment]
Sorry,  I did recreated subject. This is not reproduced with same subject. Can be closed.

Although, another one should be opened to highlight/shadow/emphasize somehow  "Soft deleted" entities on UI
