### ISSUE TITLE
Exclude aspect from aspect suggestion in special cases

### ISSUE THREAD

**Issue by samovl** [InfoWings/Knowledge-Net#386]
If Aspect has got child property with name of child aspect similar root name aspect -> root aspect is excluded form aspect suggestion everywhere (add aspect property/ add object property)
Example:
There are aspects:
**Liquid flow**
**Liquid characteristics**
     - _Liquid flow_

In Aspect suggestion field (by type "liquid") there is only "Liquid characteristics.Liquid flow", but "Liquid characteristics" is absent. 

As result: It is impossible add "Liquid characteristics" as object property with value or as Aspect property

**Comment by underlow** [comment]
database indexes issue, worked after indexes were restored
