### ISSUE TITLE
Incorrect object pagination

### ISSUE THREAD

**Issue by tushkanova** [InfoWings/Knowledge-Net#413]
Wrong quantity of items per page when some filters are applied.

**Comment by underlow** [comment]
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/15636461/52952969-37c13d00-3397-11e9-8458-41f5ccfc8842.png">

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/15636461/52952982-3f80e180-3397-11e9-9537-372c8e4fd635.png">

**Comment by tushkanova** [comment]
![image](https://user-images.githubusercontent.com/28750408/52953031-5fb0a080-3397-11e9-8796-8ba6fb1043be.png)
![image](https://user-images.githubusercontent.com/28750408/52953045-6808db80-3397-11e9-9555-bbba9362cf82.png)
