### ISSUE TITLE
Failed test: Description icon

### ISSUE THREAD

**Issue by airtest-qa** [InfoWings/Knowledge-Net#438]
Some object on the object list.

1. Open object list page.
Expected Result:
Description icons should be placed near every object.
2. Apply filtering by subject to object list.
Expected Result:
Description icons should be placed near every object of filter results.
3. Search some object with search input.
Expected Result:
Description icons should be placed near every object of search results.

Actual result:
There are no description icons neither after filtering nor after search.

T2635: Description icon
https://airtest.testrail.io/index.php?/tests/view/2635

**Comment by tushkanova** [comment]
![image](https://user-images.githubusercontent.com/28750408/54517126-e6927200-4971-11e9-8d78-02126b8331eb.png)
![image](https://user-images.githubusercontent.com/28750408/54517161-f8741500-4971-11e9-97e6-4c1a93ce77ce.png)
